{
  "services": [
    {
      "type": "web",
      "name": "leadpulse-backend",
      "env": "node",
      "region": "singapore",
      "plan": "free",
      "buildCommand": "cd backend && npm install && npx prisma generate && npm run build",
      "startCommand": "cd backend && npm run start",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "3000"
        }
      ]
    }
  ]
}
