[theme]
base = "light"
primaryColor = "#0EA5E9"
backgroundColor = "#F5F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B1220"
font = "sans serif"

[client]
showSidebarNavigation = false

[server]
headless = true
